[project]
name = 'Employment-Verifier'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Skill-Assessment]
path = 'contracts/Skill-Assessment.clar'
clarity_version = 3
epoch = 3.0

[contracts.Work-Achievement-Chain]
path = 'contracts/Work-Achievement-Chain.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
